#!/usr/bin/env sh

#
# This script can be used first time to start using dotfiles
#

set -e

echo "initialising dotfiles"

_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
echo "dotfiles direct : ${_DIR}"

${_DIR}/bin/dotme-start
${_DIR}/bin/dotme

cd ${_DIR}
export PATH=${_DIR}/bin:${PATH}
${_DIR}/bin/git-remote-to-ssh
