tap "homebrew/cask-fonts"

#
# The awesome Hack Nerd fonts combining the Hack source code font
# -  https://github.com/source-foundry/Hack
# with the Nerd aggregation of icons - https://www.nerdfonts.com/
#
cask "font-firacode-nerd-font"
cask "font-jetbrainsmono-nerd-font"
cask "font-inconsolata-nerd-font"

#
# core tools
#
# - bat - a prettier cat
# - coreutils - gnu core utilities
# - fd - alternative to find
# - fish - friendly interactive shell
# - mas - mac app store command line
# - stow - link farming
# - the_silver_searcher - ack, recursive grep alternative a.k.a ag
# - tmux - terminal multiplexer

brew "ack"
brew "bat"
brew "broot"
brew "coreutils"
brew "ctags"
brew "dos2unix"
brew "fasd"
brew "fd"
brew "findutils"
brew "fish"
brew "gnupg"
brew "lastpass-cli"
brew "mas"
brew "neovim"
brew "nmap"
brew "nnn"
brew "ripgrep"
brew "speedtest-cli"
brew "stow"
brew "switchaudio-osx"
brew "thefuck"
brew "the_silver_searcher"
brew "tmux"
brew "tree"
brew "vim"
brew "watch"

cask "iterm2"
cask "kitty"
cask "keybase"

#
# linitng tools
#

brew "yamllint"
brew "languagetool"

#
# supporting tools
#
# - fzf - fuzzy file name searcher, powering vi plugin

brew "fzf"

#
# macos tools
#
# * duti - externision to tool mapping configuration
# * dozer - menubar optimisation
#

brew "duti"

cask "alfred"
cask "dozer"
cask "evernote"

#
# office tools
#
# * pandoc + basictex => doc conversion, e.g. markdown to PDF
#
brew "pandoc"
# pandoc-citeproc,basictex disabled for now since password prompt appearing
# after this in brew install, need to troubleshoot why.
#brew "pandoc-citeproc"
#cask "basictex"
cask "drawio"

#
# dev tools
#

brew "docker-compose"
brew "gh"
brew "git"
brew "gradle"
brew "jenv"
brew "jq"
brew "k9s"

brew "maven"
brew "neofetch"
brew "nvm"
brew "rbenv"
brew "node"
brew "warrensbox/tap/tfswitch"
brew "yarn"

cask "docker"
cask "google-cloud-sdk"
cask "lens"
cask "visual-studio-code"

#
# media tools
#

brew "catimg"
brew "eye-d3"
brew "ffmpeg", args: ["with-libvpx"]
brew "imagemagick", args: ["with-webp"]
