tap "homebrew/cask-fonts"

#
# The awesome Hack Nerd fonts combining the Hack source code font -  https://github.com/source-foundry/Hack
# with the Nerd aggregation of icons - https://www.nerdfonts.com/
#
cask "font-hack-nerd-font"

brew "ack"
brew "broot"
brew "dos2unix"
brew "duti"
brew "eye-d3"
brew "fasd"
brew "fd"
brew "ffmpeg", args: ["with-libvpx"]
brew "findutils"
brew "fish"
brew "fzf"
brew "git"
brew "gradle"
brew "gnupg"
brew "imagemagick", args: ["with-webp"]
brew "jenv"
brew "macvim"
brew "maven"
brew "nvm"
brew "nmap"
brew "rbenv"
brew "node"
brew "stow"
brew "terraform"
brew "tmux"

brew "yarn"

cask "docker"
cask "iterm2"
