tap "homebrew/cask-fonts"

# The awesome Hack Nerd fonts combining the Hack source code font
# -  https://github.com/source-foundry/Hack
# with the Nerd aggregation of icons - https://www.nerdfonts.com/
#
# cask "font-firacode-nerd-font"
cask "font-inconsolata-nerd-font"

#
# core tools
#
# - bat - a prettier cat
# - coreutils - gnu core utilities
# - fd - alternative to find
# - fish - friendly interactive shell
# - mas - mac app store command line
# - stow - link farming
# - the_silver_searcher - ack, recursive grep alternative a.k.a ag
# - tmux - terminal multiplexer

brew "ack"
brew "bash"
brew "bat"
brew "bats-core"
brew "broot"
#brew "busted"
brew "coreutils"
brew "dos2unix"
brew "exa"
brew "fasd"
brew "fd"
brew "findutils"
brew "fish"
brew "glow"
brew "gnupg"
brew "htop"
brew "httpie"
brew "lastpass-cli"
brew "mas"
brew "code-minimap"
brew "neovim"
brew "nmap"
brew "nnn"
# brew "podman"
brew "ripgrep"
brew "speedtest-cli"
brew "stow"
brew "switchaudio-osx"
brew "the_silver_searcher"
brew "thefuck"
brew "tig"
brew "tmux"
brew "tree"
brew "universal-ctags"
brew "vim"
brew "watch"
brew "wget"

# cask "keybase"
cask "kitty"

#
# linitng tools
#

# brew "languagetool"
brew "yamllint"

#
# supporting tools
#
# - fzf - fuzzy file name searcher, powering vi plugin

brew "fzf"

#
# macos tools
#
# * duti - externision to tool mapping configuration
#

brew "duti"

cask "alfred"
cask "hiddenbar"

#
# office tools
#
# * pandoc + basictex => doc conversion, e.g. markdown to PDF
#
brew "pandoc"

# pandoc-citeproc,basictex disabled for now since password prompt appearing
# after this in brew install, need to troubleshoot why.
#brew "pandoc-citeproc"
#cask "basictex"
cask "drawio"

#
# dev tools
#

brew "gh"
brew "git"
brew "gradle"
brew "jenv"
brew "jq"
brew "nvm"
brew "k9s"

brew "maven"
brew "neofetch"
brew "rbenv"
# brew "warrensbox/tap/tfswitch"

cask "google-cloud-sdk"
cask "lens"

#
# media tools
#

brew "catimg"
brew "eye-d3"
# brew "ffmpeg", args: ["with-libvpx"]
# brew "imagemagick", args: ["with-webp"]
