FROM alpine:latest

# Commands used for explority testing
RUN echo dotme >> /root/.bash_history
RUN echo dotme full >> /root/.bash_history
RUN echo bash >> /root/.ash_history
RUN echo /root/.dotfiles/start >> /root/.ash_history
