# Homebrew packages that require password to install

#
# Development
#
brew "openjdk@11"

# Disable adoptopenjdk8 until resolution to ..
# https://github.com/AdoptOpenJDK/homebrew-openjdk/issues/106
# Error: Cask adoptopenjdk8 exists in multiple taps:
#cask "adoptopenjdk8"
#cask "adoptopenjdk11"
#cask "java11"
