#!/bin/sh

#
# Main branch protection, always go via branch
#
remote="$1"
url="$2"

branch=$(git rev-parse --abbrev-ref HEAD)

if [[ "$branch" == "main" ]] ; then
  echo "Please create a branch from main before pushing"
  exit 1
fi
