#!/bin/sh

#
# Main branch protection, always go via branch
#
branch=$(git rev-parse --abbrev-ref HEAD)

if [[ "$branch" == "main" ]] ; then
  echo "Please create a branch from main before committing"
  exit 1
fi
