plugins:
  remark-preset-lint-recommended:
  # Favor consistency
  remark-preset-lint-consistent:
  remark-frontmatter:
  # GitHub Flavoured Markdown
  remark-gfm:
  lint-list-item-indent: "space"
  # Allow email and www links direct (they are less verbose)
  lint-no-auto-link-without-protocol: false
  lint-unordered-list-marker-style: "consistent"

settings:
  bullet: "-"
  listItemIndent: "one"
