name: test

on: [push, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: node tests
        working-directory: ./test
        run: |
          npm install
          npm test

  test-py:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.9]

    steps:
      - uses: actions/checkout@v1
      - name: set up python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: install pythong dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest pytest-bdd
      - name: lint with flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: python tests
        run: |
          pytest

  test-dotme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name:
        run: |
          sudo apt-get install stow
          rm ~/.bashrc
          rm ~/.bash_profile
          ./bin/dotme -i "shim|stow"
          ./start
          . $HOME/.bash_profile
          . $HOME/.bashrc
          ./bin/dotme verify

  test-vim:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        neovim: [false, true]
        version: [stable]
        #include:
        #  - neovim: true
        #    version: nightly

      fail-fast: false

    steps:
      - uses: actions/checkout@v1
      - name: checkout vader.vim
        uses: actions/checkout@v2
        with:
          repository: junegunn/vader.vim
          path: ./test/vim/tmp/vim/plugins/vader.vim
      - uses: rhysd/action-setup-vim@v1
        id: vim
        with:
          neovim: ${{ matrix.neovim }}
          version: ${{ matrix.version }}
      - name: test
        env:
          VIM_COMMAND: ${{ steps.vim.outputs.executable }}
        working-directory: ./test/vim
        run: |
          echo $VIM_COMMAND
          make test
