name: test

on: [push, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.22.2
      - name: node tests
        working-directory: ./test
        run: |
          pnpm install
          pnpm test

  test-dotme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name:
        run: |
          sudo apt-get install stow
          rm ~/.bashrc
          rm ~/.bash_profile
          ./bin/dotme -i "shim|stow|bash"
          ./start
          . $HOME/.bash_profile
          . $HOME/.bashrc
          ./bin/dotme verify

  test-vim:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        neovim: [false, true]
        version: [stable]
        #include:
        #  - neovim: true
        #    version: nightly

      fail-fast: false

    steps:
      - uses: actions/checkout@v1
      - name: checkout vader.vim
        uses: actions/checkout@v2
        with:
          repository: junegunn/vader.vim
          path: ./test/vim/tmp/vim/plugins/vader.vim
      - uses: rhysd/action-setup-vim@v1
        id: vim
        with:
          neovim: ${{ matrix.neovim }}
          version: ${{ matrix.version }}
      - name: test
        env:
          VIM_COMMAND: ${{ steps.vim.outputs.executable }}
        working-directory: ./test/vim
        run: |
          echo $VIM_COMMAND
          make test
