name: test

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
      - name: test
        run: |
          test/vim/test-vimrc.sh
