name: test

on: [push, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - name: Setup Bats and bats libs
        uses: bats-core/bats-action@1.5.4
      - name: tests
        working-directory: ./test
        run: |
          bats -T fixtures

  test-dotme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - name:
        run: |
          echo $SHELL
          sudo apt-get install stow
          rm ~/.bashrc
          rm ~/.bash_profile
          ./bin/dotme -i "shim|stow"
          ./start
          . $HOME/.bash_profile
          . $HOME/.bashrc
          ./bin/dotme verify

  test-vim:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        neovim: [false, true]
        version: [stable]
      fail-fast: false

    steps:
      - uses: actions/checkout@v3.3.0
      - name: checkout vader.vim
        uses: actions/checkout@v3.3.0
        with:
          repository: junegunn/vader.vim
          path: ./test/vim/tmp/vim/plugins/vader.vim
      - uses: rhysd/action-setup-vim@v1
        id: vim
        with:
          neovim: ${{ matrix.neovim }}
          version: ${{ matrix.version }}
      - name: test
        env:
          VIM_COMMAND: ${{ steps.vim.outputs.executable }}
        working-directory: ./test/vim
        run: |
          echo $VIM_COMMAND
          make test
