name: test

on: [push, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        neovim: [false, true]

    steps:
      - uses: actions/checkout@v1
      - name: Checkout vader.vim
        uses: actions/checkout@v2
        with:
          repository: junegunn/vader.vim
          path: .config/nvim/plugged/vader.vim
      - uses: rhysd/action-setup-vim@v1
        with:
          neovim: ${{ matrix.neovim }}
      - name: test
        env:
          VIM_COMMAND: ${{ steps.vim.outputs.executable }}
        run: |
          make test
      - name: report on fail
        if: ${{ failure() }}
        run: |
          ls
          pwd
          cat vader.log
