name: test

on: [push, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup BATS
        uses: mig4/setup-bats@v1
        with:
          bats-version: 1.2.1
      - uses: actions/checkout@v1
      - name:
        working-directory: ./test
        run: |
          sudo apt-get install bats-core
          make test

  test-dotme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name:
        run: |
          sudo apt-get install stow
          rm ~/.bashrc
          rm ~/.bash_profile
          ./bin/dotme -i "shim|stow"
          ./start
          . $HOME/.bash_profile
          . $HOME/.bashrc
          ./bin/dotme verify

  test-vim:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        neovim: [false, true]
        version: [stable]
        #include:
        #  - neovim: true
        #    version: nightly

      fail-fast: false

    steps:
      - uses: actions/checkout@v1
      - name: Checkout vader.vim
        uses: actions/checkout@v2
        with:
          repository: junegunn/vader.vim
          path: ./test/vim/tmp/vim/plugins/vader.vim
      - uses: rhysd/action-setup-vim@v1
        id: vim
        with:
          neovim: ${{ matrix.neovim }}
          version: ${{ matrix.version }}
      - name: test
        env:
          VIM_COMMAND: ${{ steps.vim.outputs.executable }}
        working-directory: ./test/vim
        run: |
          echo $VIM_COMMAND
          make test
